on:
  workflow_dispatch:
  push:
  # push:
  #   # Sequence of patterns matched against refs/tags
  #   tags:
  #     - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  CHANGELOG_FILE: versioning/CHANGELOG.md
  VERSION_FILE: versioning/VERSION

name: Create Release

jobs:
  get-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: parse-changelog
        run: |
          i=0
          header_start=-1
          release_message=""

          while read p; do
              if [[ $p == \#\#\ * ]]
              then
                  if [[ $header_start -gt -1 ]]
                  then
                      break
                  fi
                  header_start=$i
              fi

              if [[ $header_start -gt -1 ]]
              then
                  release_message="$release_message\n$p"
              fi
              ((i=i+1))
          done < $CHANGELOG_FILE

          echo "::set-output name=latestSection::$release_message"
          echo "$release_message"
      
      - id: get-version
        run: echo "::set-output name=version::$(cat $VERSION_FILE)"

      - name: Unescape special characters
        run: printf "${{ steps.parse-changelog.outputs.latestSection }}" > unescaped-release-notes.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: v${{ steps.get-version.outputs.version }}
          body_path: unescaped-release-notes.md